---
# File: ../tasks/main.yml
# Main tasks file for apache-modsecurity

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family | lower }}.yml"
  tags:
    - configuration

# Setup/install tasks.
- include_tasks: "setup-{{ ansible_os_family | lower }}.yml"
  tags:
    - configuration
    - setup
